language: csharp

mono: none
dotnet: 2.2.0
script:
  - dotnet restore

#services:
#  - docker

cache:
  directories:
    - $HOME/.m2

before_script:
  - export CODACY_PROJECT_TOKEN=0cb79df439ec4a08b0427f452f218f68